### ISSUE TITLE
README mentions `startup_rvc`

### ISSUE THREAD

**Issue by goretkin** [petercorke/robotics-toolbox-matlab#11]
In the zip files available on http://www.petercorke.com/RTB/, this file exists, but I don't understand how to use the toolbox from a cloned git repo. 

Running `startup_rtb.m` doesn't load, for example, functions under `common`. Actually, I don't understand in which repo those functions are hosted. (For example `runscript.m`.)

**Comment by petercorke** [comment]
For historical reasons the repository layout of the toolbox is different to the distributions I push out.  There's (too) complex process to package up the distribution.  This is on my list of things to fix.

What I do is create a top level folder with startup_rvc in it, copy from an old distribution, and in that folder I have symlinks to the three git repos (robot, vision, common).

**Comment by petercorke** [comment]
Readme updated to explain this
