### ISSUE TITLE
lack of numcols function

### ISSUE THREAD

**Issue by wubobupt** [petercorke/robotics-toolbox-matlab#15]
when i run a command >>q = Quaternion( rpy2tr(0.1, 0.2, 0.3) ) in matlab, it failed because of lack of definition of numcols function.

**Comment by fverdoja** [comment]
The toolbox-common-matlab package is a dependency of this one... it contatins the numcols function.
https://github.com/petercorke/toolbox-common-matlab
Maybe the readme could advise people to install them both?

**Comment by petercorke** [comment]
Readme updated
