### ISSUE TITLE
Please mark release number Milestones in Github

### ISSUE THREAD

**Issue by TheBlune** [petercorke/robotics-toolbox-matlab#24]
Hey Peter,

Thanks for your work so far. 

I am needing an older Version of your Toolbox (Version 9.7) for some older MATLAB-Tool-Files. Please mark the Version-Milestones in the future, so that people can easily download older Versions of your great Toolbox. Any advice on how to download  this specific version? 

Thanks in advance!

**Comment by petercorke** [comment]
I lost most of my development history when I got booted off google code (svn) and was not able to get it into GitHub.  

You can get the old versions via my [developer page](http://petercorke.com/wordpress/toolboxes/support-developer).
