### ISSUE TITLE
Friction Co-efficients

### ISSUE THREAD

**Issue by Theesh76** [petercorke/robotics-toolbox-matlab#26]
I am trying to do parameter estimation of puma 560 using this library. I am able to get the inertial parameter estimates perfectly.

1. I have a doubt if the Bm, Tc represents coefficients of Coulomb and viscous friction respectively or does it represent maximum /minimum friction limits, for ex. Tc takes a range (like: -0.1 to +0.1) as input.  What does this number signify?

2. If  Bm, Tc is not coefficients of Coulomb and viscous friction respectively. Is there a way to calculate the coefficients using gear ratios, Tc, Bm?

3. Is stribeck, stiction modelled in puma 560 and is it visible at low-velocity?

Thanks in advance

**Comment by petercorke** [comment]
Sorry for long delay, I need to add this list to my roster.  Have a look at Link.friction() which defines the model.  There is no Stribeck model, just non-symmetric Coulomb + viscous friction.  You could add arbitrary complexity to the friction model in Link.friction().

Are you willing to share your inertial parameter estimation code, it's been on my TODO list for RTB for a long time.
