### ISSUE TITLE
 DHFactor Error !

### ISSUE THREAD

**Issue by lyhbuaa** [petercorke/robotics-toolbox-matlab#29]
When I run the example in 7.4.2 for determining the Dh factors, i met the error

```
Attempt to execute SCRIPT DHFactor as a function:
D:\Program Files\MATLAB\R2013a\toolbox\rvctools\robot\DHFactor.m
```

my command is
```
s = 'Tz(L1) Rz(q1) Ry(q2) Ty(L2) Tz(L3) Ry(q3) Tx(L4) Ty(L5) Tz(L6) Rz(q4) Ry(q5) Rz(q6)'
dh = DHFactor(s)
```

Is anyone else met this error and how to deal with it？

**Comment by petercorke** [comment]
this is Java code so you need to put the .class path into the MATLAB Java path.  Run startup_rvc or do this manually.

**Comment by lyhbuaa** [comment]
@petercorke ok, thank you very much! I have solved this problem. Then I have another question, but I found that this git is not active, is there any other forum for us to discuss a problem, or please tell me your e-mail, so I can I can contact you directly？

**Comment by petercorke** [comment]
tiny.cc/rvcforum <http://tiny.cc/rvcforum>

**Comment by lyhbuaa** [comment]
@petercorke I am sorry, I can not open this URL in china..................

**Comment by petercorke** [comment]
Can you open this version of the URL

https://groups.google.com/forum/?hl=en#!forum/robotics-tool-box

peter
