### ISSUE TITLE
codegen demo fails

### ISSUE THREAD

**Issue by joernmalzahn** [petercorke/robotics-toolbox-matlab#32]
The code generation demo ```\demos\codegen.m``` fails in at least two points. Both are related to the recently introduced SE class framework.

- [ ] ```codegen.m``` line 130: ```tic; Tz2 = specRob.fkine(qz); t2 = toc``` Here we have qz being an SE [1x3] class instance. The symbolic toolbox does not understand, how to substitute this.

- [ ] ```codegen.m``` line 204: ```J02 = specRob.jacob0(qz)``` A breakpoint inside jacob0.m reveals that the fkine method for some reason returns a [4x4] matrix instead of an SE class instance. Hence the dot notation in line 73 (```jacob0.m```) fails. Strange enough, the previous call to jacob0 does not cause this issue.

All other lines in ```codegen.m``` pass.

**Comment by petercorke** [comment]
Fixed in 10.3.1
