### ISSUE TITLE
Animate is not defined

### ISSUE THREAD

**Issue by lyhbuaa** [petercorke/robotics-toolbox-matlab#33]
Recently, I used the plot3d function, and select the 'movie' option as 'my.mp4', but I met the error 'Animate is not defined',
    I really did not find the relevant file or function definition in the toolbox.
    How can we solve this problem?

**Comment by quanvuong** [comment]
I'm having a similar problem of running EKF. 

>> ekf.run(1000, 100);
Undefined function or variable 'Animate'.

Error in EKF/run (line 407)
            anim = Animate(opt.movie);

**Comment by petercorke** [comment]
This was left out of the 10.3 distro, added to 10.3.1 on the website.  This class lives in the toolbox-common repo.
