### ISSUE TITLE
Error in SerialLink/plot3d (line 154)

### ISSUE THREAD

**Issue by oladayosolomon** [petercorke/robotics-toolbox-matlab#43]
Index exceeds matrix dimensions.

Error in SerialLink/plot3d (line 154)
            opt.ws(5) = mn(3);

**Comment by Dps8** [comment]
Does this error only occur in this version of the robotic toolbox?

**Comment by petercorke** [comment]
Please send a complete example that demonstrates the error, otherwise all I can say is it works for me.

**Comment by Dps8** [comment]
![problem](https://user-images.githubusercontent.com/46031424/52413905-d654c080-2ab0-11e9-8994-5093a8ddcde1.jpg)

**Comment by Dps8** [comment]
This is the error he gives me. Now I know for your classes, Professor Corke, that does not happen to you. Any suggestions

**Comment by petercorke** [comment]
Your query comes via GitHub so I guess you installed by cloning the repo?  The path setup is not quite right.  Did you run startup_rtb first?

peter

**Comment by Dps8** [comment]
I did not clone the repos, I used the * .mltb file to install the toolbox in Matlab.

**Comment by Dps8** [comment]
Do I have to use the startup_rtb command anyway? Because other commands do work for me without using this one.

**Comment by petercorke** [comment]
Interesting.  I’ll have a look at this over the weekend, am travelling this week.

**Comment by petercorke** [comment]
If you install from the mltbx file the paths should be setup.  There is also a script called startup_rvc which should do the job for all my toolboxes that are installed.

**Comment by Dps8** [comment]
ok professor, I wait for your answer, I'm going to try cloning the repos to see if the error persists. Please you contact me if you discover the cause of the error. Greetings from Cuba.

**Comment by petercorke** [comment]
Please remove the MATLAB Phased Array Toolbox from your installation, or else use path tool to put it absolutely last in the path.  That will fix your problem, but also eliminate many other possible errors.

**Comment by Dps8** [comment]
thank you very much profesor, it works well.
