### ISSUE TITLE
'path' is not an accessble method of base Class 'Navigation'      

### ISSUE THREAD

**Issue by UsamaHamayun1** [petercorke/robotics-toolbox-matlab#53]

**Comment by UsamaHamayun1** [comment]
Hello , 
 i am trying to Run Astar.m code Example 1 written in The comment and when i write as.path(start) it gives error 'path' is not accessible method of The base class navigation

**Comment by petercorke** [comment]
This was contributed to the toolbox but is not actively maintained by the contributor or me.  The Navigation superclass method changed to query() in RTB10.  If you want to update it please send a pull request.
