### ISSUE TITLE
Creating Link object without DH parameters

### ISSUE THREAD

**Issue by aminya** [petercorke/robotics-toolbox-matlab#54]
Can I use Link object to create a link without using DH parameters (like using custom transformation matrix and frames)?  if so, how? if not we should add an option to the class.

**Comment by petercorke** [comment]
The DH notation is fundamentally limiting.  I want to make a backward compatible change to SerialLink that supports a chain of general URDF-type transformations.  This is the link branch but I've not had the time to push it far.
