### ISSUE TITLE
Error using codegenerator to generate jacob0 with rpy

### ISSUE THREAD

**Issue by santdiego** [petercorke/robotics-toolbox-matlab#55]
I can not generate the Jacobian matrix of a robot with rpy representation with CodeGenerator 
I tried to modify line 59 of "genjacobian.m" to use rpy:
`J0 = CGen.rob.jacob0 (q, 'rpy');`
But I get the following error when generating the Jacobian:
> Conversion to logical from sym is not possible.
> Error in tr2rpy (line 110)
>             if abs(abs(R(3,1)) - 1) < eps  % when |R31| == 1
> 
> Error in SO3/tr2rpy (line 278)
>             rpy = tr2rpy(obj.R, varargin{:});
> 
> Error in SerialLink/jacob0 (line 84)
>                 rpy = tr2rpy(Tn);
> 
> Error in CodeGenerator/genjacobian (line 59)
> J0 = CGen.rob.jacob0(q,'rpy');

It seems that the underlying problem is that the tr2rpy() function does not work with symbolic expressions, for example :
```
syms r p y
T=rpy2tr(r,p,y)
rpy=tr2rpy(T)
```

> Conversion to logical from sym is not possible.
> 
> Error in tr2rpy (line 110)
>             if abs(abs(R(3,1)) - 1) < eps  % when |R31| == 1

**Comment by petercorke** [comment]
the algorithm contains logic not just algebra so can’t be expressed symbolically.

why do you need to use an analytic Jacobian, RPY angles is a poor representation and subject to singularity.

peter
