### ISSUE TITLE
ctraj function

### ISSUE THREAD

**Issue by NataCalc** [petercorke/robotics-toolbox-matlab#61]
Hi Peter,

I am using ctraj function to interpolate my data (Transformation matrix of displacement and rotation). Is there the way to improve the interpolation from step 1 to step 5 performed by ctraj function? In figures, grey corresponds to initial positions of two objects. From this position, objects displace and rotate. 

![Step1](https://user-images.githubusercontent.com/47018678/63240248-2eefec00-c292-11e9-9942-441a76272881.png)
![Step2](https://user-images.githubusercontent.com/47018678/63240250-2eefec00-c292-11e9-8ba7-441cfbac290e.png)
![Step3](https://user-images.githubusercontent.com/47018678/63240251-2eefec00-c292-11e9-8819-c404b032bdc4.png)
![Step4](https://user-images.githubusercontent.com/47018678/63240253-2f888280-c292-11e9-90aa-1c13af282e40.png)
![Step5](https://user-images.githubusercontent.com/47018678/63240254-2f888280-c292-11e9-9520-1efe7e387630.png)

Cheers,
Nataliya

**Comment by petercorke** [comment]
sorry for delay, been on holiday... It's not clear what you're trying to improve, can you give me more details.  The pictures don't really help me, sorry.

**Comment by NataCalc** [comment]
Dear Peter,


I am using ctraj to interpolate my data which was derived from 4DCT scan of two bones motion in the wrist. When rotation of bones becomes significant, ctraj function interpolates in the way where bones start moving unphysiologically. I am wondering to know if there is the way to avoid this through using some control parameters?



Regards,

Nataliya

**Comment by petercorke** [comment]
So the initial and final orientation are correct, but the intermediate rotations are not what you want?

**Comment by NataCalc** [comment]
Yes, intermediate rotation and displacement are not correct.

**Comment by petercorke** [comment]
ctraj does the following:
- linear path between start and end point
- quaternion slerp interpolation of orientation between start and finish

There are an infinite number of paths between two poses and this one is sort of minimum motion.  I think the only way to get the motion you need would be to:

- spline between known good via points
- introduce kinematic constraints between the bones, perhaps one rolls over the other…

**Comment by NataCalc** [comment]
Hi Peter,

By ‘spline between start and end point’, did you mean spline interpolation (https://en.wikipedia.org/wiki/Spline_interpolation ). If so, do you have already existing code in robotic toolbox matlab?

Regards,
Nataliya

**Comment by petercorke** [comment]
The closest I have to spline code is mstraj() but it interpolates vectors not poses, so you’d have to use XYZ+RPY representation or some such.

**Comment by NataCalc** [comment]
Hi Peter,

By XYZ+RPY did you mean the vector  = translationin X,Y, Z + Roll Pitch Yaw XYZ?

Also, in traj = mstraj(p, qdmax, tseg, q0, dt, tacc, options), is p the matrix which consists of trajectory vectors associated with beginning and end of poses? Do you have in your online tutorials explanation of mstraj function?

Cheers,
Nataliya

**Comment by petercorke** [comment]
The documentation help mstraj will give you the details.  Then convert the interpolated XYZRPY vectors back to poses.  Also covered in chap 3 of my book.
