### ISSUE TITLE
Julia package port

### ISSUE THREAD

**Issue by aminya** [petercorke/robotics-toolbox-matlab#63]
Is there any plan for porting this toolbox to Julia language?

**Comment by petercorke** [comment]
A student of mine made a start on this, see

https://github.com/thomper/RoboticsToolbox.jl

Julia is a very interesting language and it would be great to complete this.  But I’m struggling just to keep the MATLAB version ticking along.

**Comment by aminya** [comment]
That has these functions:
```
rot2, rotx, roty, rotz
trot2, trotx, troty, trotz
se2, se3
r2t, t2r
rpy2r, rpy2t, rpy2jac, tr2rpy
```
To revive that project, it is needed to update the syntax from Julia 0.6 to Julia 1.2.
 There's already a handful of robotics packages in Julia: http://www.juliarobotics.org/ and https://github.com/JuliaRobotics .

So, I was thinking of moving some useful parts of Robotics toolbox to that collection and move it to Julia. So not everything is needed to be transferred.

**Comment by petercorke** [comment]
Feel free to update and integrate into JuliaRobotics.  Let me know when it's done.
