### ISSUE TITLE
3Link robot arm control by Matlab and Simulink

### ISSUE THREAD

**Issue by bearshawn** [petercorke/robotics-toolbox-matlab#65]
Hi I am building a three links (3DOF) robot arm, and each link works by servo motor. And at the end-effector is a DC motor to do the drilling. I would like to control it by Matlab and do the simulation on Simulink as well. 
Is there any Matlab code that I can apply  for this project?
Also, is there any Simulink file that is match what I need?

I am looking forward to get some responses.
Hope I can get some help.

**Comment by petercorke** [comment]
you might do better in tiny.cc/rvcforum which is the discussion group for the toolbox and related.  There are quite a few Simulink models discussed in my book, and included in the simulink folder of this repo.
