### ISSUE TITLE
Function or variable 'AE' is not defined.

### ISSUE THREAD

**Issue by QNjeason** [petercorke/robotics-toolbox-matlab#74]
I run the following code with the following error.
`mdl_puma560`
`p = [0.8 0 0];`
`T = transl(p) * troty(pi/2);`
`qr(1) = -pi/2;`
`qqr = p560.ikine6s(T, 'ru');`
`qrt = jtraj(qr, qqr, 50);`
`plot_sphere(p, 0.05, 'y');`
`p560.plot3d(qrt, 'view', ae, 'movie', 'move2ball.gif'); `

Function or variable 'AE' is not defined.
未定义函数或变量 'ae'。
出错 test (line 15)
p560.plot3d(qrt, 'view', ae, 'movie', 'move2ball.gif');

**Comment by petercorke** [comment]
where did this code snippet come from?  Make the last line

p560.plot3d(qrt, 'movie', 'move2ball.gif');

**Comment by QNjeason** [comment]
thank you answer.

**Comment by petercorke** [comment]
Where did you paste that example from?

**Comment by QNjeason** [comment]
I copied it from this page.
https://github.com/petercorke/robotics-toolbox-matlab
![image](https://user-images.githubusercontent.com/52246049/83007529-68862c80-a046-11ea-81a1-d91e1adff64e.png)
Please also correct the sample program for this problem.

**Comment by omeryusufyagci** [comment]
This issue was closed but the wiki remains unchanged. You can find this code snippet under "readme.md".  The first sample code under the title "Code Example" does not work as-is.
