### ISSUE TITLE
Broken referenced Link

### ISSUE THREAD

**Issue by mithi** [petercorke/robotics-toolbox-matlab#76]
The link referenced here is unfortunately broken. 😞 
https://github.com/petercorke/robotics-toolbox-matlab/blob/6c528c5ca4c00adc58e2852f4d86466e5e02b673/RobotArm.m#L29

- http://www.petercorke.com/doc/robotarm.pdf

**Comment by petercorke** [comment]
pls replace it with this one https://petercorke.com/matlab/interfacing-a-hobby-robot-arm-to-matlab/

**Comment by mithi** [comment]
Thanks!

**Comment by mithi** [comment]
❤️ 🥳 🎊 🍾
