### ISSUE TITLE
Bug in the command rpy2r() in version 10.1

### ISSUE THREAD

**Issue by Kalana304** [petercorke/robotics-toolbox-matlab#78]
Based on the given documentation, **rpy2r()** command computes the angles as radians. 
![image](https://user-images.githubusercontent.com/54796890/82592026-dac9bd80-9bbd-11ea-9f1d-28f735b12446.png)

I have run the command as following and obtained the following result as shown in the screenshot. 
![image](https://user-images.githubusercontent.com/54796890/82592116-0a78c580-9bbe-11ea-9d1d-3a9f55e8c7b3.png)

Using the basic rotation matric transformations i obtained the following results for the same angle transformation.
![image](https://user-images.githubusercontent.com/54796890/82592247-3e53eb00-9bbe-11ea-811e-d3a5713cfe40.png)

which you can see that the two results are not the same. 

I then ran the **t2rpy()**  to verify what would be the resulting euler angles for the given rotation matrix.
![image](https://user-images.githubusercontent.com/54796890/82592898-39dc0200-9bbf-11ea-9aad-2312b1b57dcf.png)

which means when the **'deg'** option is given the angles are converted to radians but still are considered as degrees. 
Without **'deg'** option in rpy2r(), the output seems to be calculated with degrees which given same answer as to the one obtained from basic rotation matrices. 
![image](https://user-images.githubusercontent.com/54796890/82593234-c981b080-9bbf-11ea-8a63-d854a9023991.png)

My MatLab version is 2016a. Better to revise the documentation provided and correct it.

**Comment by Kalana304** [comment]
I think the followinf script shows the issue.
![image](https://user-images.githubusercontent.com/54796890/82595873-fc2da800-9bc3-11ea-8935-0b8a79b6665e.png)
the basic rotation matrices take angles as degrees by default. Here the given angles are converted into radians if the opt.deg is True.

**Comment by petercorke** [comment]
Check your path, you probably have rotx() coming from the phased array toolbox. This I on the FAQ at the google group support forum.
